### ISSUE TITLE
Please add a LICENSE file.

### ISSUE THREAD

**Issue by pserwylo** [adityajo/sarcasmbot#2]
Just watched the presentation at KDD, well done guys. Could you please add a `LICENSE` file to the repo to make good of your claim about "An _open-source_ sarcasm-generation module for chatbots".

**Comment by adityajo** [comment]
Hi Peter,

This is my first github repo. I have missed adding installation
instructions too. Thanks for telling me about the license. I will add it.

Regards,
Aditya

_if you can read this... thank a Teacher (Source: Unknown)_

2015-08-10 12:23 GMT+05:30 Peter Serwylo notifications@github.com:

**Comment by pserwylo** [comment]
> I have missed adding installation instructions too

No worries, Merge Request #1 should fix that for you :)

**Comment by adityajo** [comment]
Hi,
I have added the license, and installation instructions.

Regards,
Aditya

_if you can read this... thank a Teacher (Source: Unknown)_

2015-08-11 8:31 GMT+05:30 Peter Serwylo notifications@github.com:
